### ISSUE TITLE
numLoop on empty intervals

### ISSUE THREAD

**Issue by Daniel-Diaz** [nh2/loop#3]
Let `n :: Int` be an integer strictly greater than `m`, and `f :: Monad m => Int -> m ()`. Then, `numLoop n m f` does this:

```
do f  n
   f (n+1)
   f (n+2)
   f (n+3)
   ...
```
In the case of `Int` this will reach `maxBound`, then `minBound`, and then will go straight to `m`. In the case of `Integer` it will never end. In any case, I think this is undesirable.

I propose either warning of this in the docs or testing if `n <= m` before looping and doing nothing if it returns `False`.

Note that the behavior I propose will fit much better the semantics of `forM_ [n..m] f`, because `[n..m] = []` whenever `n > m`.

**Comment by nh2** [comment]
Done. https://hackage.haskell.org/package/loop-0.3.0
