### ISSUE TITLE
loop in Stackage

### ISSUE THREAD

**Issue by Daniel-Diaz** [nh2/loop#7]
It would be useful if `loop` was added to Stackage.

Thanks!

**Comment by nh2** [comment]
OK: https://github.com/fpco/stackage/pull/1501

**Comment by Daniel-Diaz** [comment]
Thanks!

**Comment by nh2** [comment]
Looks like we have to wait for `foldl` to be GHC-8 ready though

**Comment by nh2** [comment]
Done. https://www.stackage.org/nightly-2016-06-08
