### ISSUE TITLE
`forLoop` cannot break in the middle

### ISSUE THREAD

**Issue by yaitskov** [nh2/loop#9]
Hi,

`forLoop` function is positioned as drop-in replacement for C-style `for`, but it doesn't posses very important property, which original C version does - ability to break in the middle. 
`forLoop` condition is a pure function independent of body, so there is no way to break in the middle except by throwing an exception:

```
for (int i = 0; i < 10; ++i ) {
   if (doIo()) {
      i = 10;
   }
}
```

I am not sure about signature, but my suggestion would be:

```
forLoop :: Monad m => a -> (a -> Bool) -> (a -> a) -> (a -> m ()) -> m () 
----
forLoop :: Monad m => a -> (a -> Bool) -> (a -> a) -> (m () -> a -> m ()) -> m () 
```

The first (extra) body argument is an action to called for breaking the loop.

**Comment by nh2** [comment]
Hey,

`loop`'s main goal is not to provide the full interface of C loops, but to provide easy replacements for `forM_ [1..N]` that do not suffer from performance problems resulting from lack of optimisation, and to provide a benchmark for testing that case.

All `loop` functions are implemented as simple `go`-style recursive functions ([example](https://hackage.haskell.org/package/loop-0.3.0/docs/src/Control-Loop.html#forLoop)). If you need a custom exit condition, I believe it is much better to explicitly write down the recursive `go` function explicitly: This provides better readability, and more flexible control flow (for example, C also has `continue;`), and less ambiguity (as you point out, there are various ways one can type an implement such functionality, and none is perfect for all use cases).

Closing for that reason for now.
